### ISSUE TITLE
Support for multiple services on single server?

### ISSUE THREAD

**Issue by thedodd** [tokenio/grpc-actix#23]
Looks like some awesome work so far. Does the system support registering multiple services on the same server?

**Comment by sphw** [comment]
It _should_ work. In the `sys.block_on` block you can add as many `ServiceDispatch::add_to_service` calls as you want. I am not sure if we have properly tested using multiple services, and so if it doesn't work feel free to file an issue. 

I would warn that we haven't updated our this library in a while. Actix itself is still on `futures` 0.1, and has been dropped by the `actix-web`. Tower seems like a good and well maintained alternative, though it doesn't have the same concurrency model as `Actix`.

**Comment by thedodd** [comment]
Yea, tower doesn’t support multiple services currently. Are you all planning on maintaining this crate? I tend to prefer actix based systems, as the flexibility it provides is outstanding.

**Comment by okready** [comment]
I'm not sure myself unless @sphw has any plans on his own. We might be re-evaluating it in relation to the state of other gRPC implementations in the next couple months, but nothing in particular has been planned yet.

**Comment by thedodd** [comment]
Cool. Also, the readme doesn’t seem to indicate that this crate has a bunch of outstanding work remaining to be done. Is that true? Is the full gRPC spec supported?

**Comment by okready** [comment]
Much of the core [gRPC HTTP2](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) functionality is there, but a lot of features haven't been tested much, if at all (technically, the crate was never released, and we eventually had to shift focus elsewhere). There's very likely also cases where we're not properly following the spec, so compatibility of existing features with other gRPC servers or clients isn't guaranteed. Streaming support is there, but we weren't using it in our own projects at the time, so I'm not sure what cases there might be where it falls apart.

There are some features that definitely aren't implemented though:
- Content types other than the standard protobuf encoding. The server currently ignores the content type indicated in a request and always tries to process requests as protobuf data.
- [Compression](https://github.com/grpc/grpc/blob/master/doc/compression.md) (both in the client and the server).
- [gRPC Web](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md).
- Any other feature not covered in the main gRPC HTTP2 specification (e.g. [health checking](https://github.com/grpc/grpc/blob/master/doc/health-checking.md), [reflection](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md), [wait for ready](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md)).

**Comment by thedodd** [comment]
@okready thanks for the overview, I appreciate it!
